name: "Vault Secrets"
description: "Expose build secrets stored in Vault to your jobs"
author: "@mikeknox"
public: true
requirements:
  - curl
  - bash
  - vault
configuration:
  properties:
    server:
      type: string
  required:
    - server
  additionalProperties: false

